### ISSUE TITLE
Configurar o ambiente do Pnetlab

### ISSUE THREAD

**Issue by Maxuelbm** [Maxuelbm/ISP-Toolbox#1]
Criar máquina virtual e instalar a aplicação do Pnetab.

**Comment by fredericont** [comment]
Realizada a instalação do PnetLAB em servidor destinado a hospedar este serviço, e após redirecionamento de portas feito por Maxuel, validado o acesso via browser. 

![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/104873596/a2323912-1253-4f7d-ac7f-f3254d766767)

**Comment by fredericont** [comment]
Criado usuário para acesso, e definidos as seguintes credenciais: 
user: ProjetoPnetlab
password: Pr0j3t01nt3gr4d0r
