### ISSUE TITLE
Criar os profiles dos clientes.

### ISSUE THREAD

**Issue by Maxuelbm** [Maxuelbm/ISP-Toolbox#11]
Criar os profiles dos PCs clientes com as velocidades do serviço.

**Comment by fredericont** [comment]
Profiles criados via acesso WinBox, e vinculados aos PPPoE
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/104873596/5bad1a65-da03-4cb1-ae27-76f9fa43674b)
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/104873596/5c38810d-dc26-4369-af39-f9016cfc9df1)
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/104873596/522d6a38-cebc-48f6-be4b-a6f8b48901d4)
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/104873596/3fa70624-e856-4c84-b5ac-dbda3503370d)
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/104873596/05b5f855-fdaa-4a16-94d5-78f68e3fb80d)

As informações de logins e os dados dos planos são dados fictícios, apenas para simulação.
