### ISSUE TITLE
Configurar o serviço do PPPoE para todos os clientes do ambiente.

### ISSUE THREAD

**Issue by Maxuelbm** [Maxuelbm/ISP-Toolbox#12]
Realizar a configuração para atender todos os PCs clientes da topologia.

**Comment by Maxuelbm** [comment]
Conectividade dos clientes:

- [x] Cliente 1
- [x] Cliente 2
- [x] Cliente 3
- [x] Cliente 4
- [x] Cliente 5
- [x] Cliente 6

**Comment by wellyngton-sena** [comment]
A configuração dos roteadores clientes foi concluída com sucesso, empregando o script a seguir. Este script não apenas configura interfaces, políticas de firewall, masquerade e endereços IP, mas também realiza a discagem do PPPoE. Vale ressaltar que, embora haja variação nos logins PPPoE, nos IPs e nas interfaces, a estrutura da configuração permanece.

RT - CLIENTE 1 emprega o PPPoE com o usuário "joao" e senha correspondente. RT - CLIENTE 2 utiliza o PPPoE com credenciais associadas a "maria" como usuário e senha. RT - CLIENTE 3 faz uso do PPPoE, autenticando-se com o usuário "delcimir" e a senha correspondente.

```
/interface ethernet
set [ find default-name=ether1 ] comment=SW-ACESSO
set [ find default-name=ether4 ] comment=GERENCIA
set [ find default-name=ether2 ] comment=CLIENTE
/interface pppoe-client
add add-default-route=yes allow=chap,mschap1,mschap2 disabled=no interface=ether1 name=link password=delcimir use-peer-dns=yes user=delcimir
/interface wireless security-profiles
set [ find default=yes ] supplicant-identity=MikroTik
/ip pool
add name=dhcp_pool0 ranges=192.168.0.2-192.168.0.254
/ip dhcp-server
add address-pool=dhcp_pool0 disabled=no interface=ether2 name=dhcp1
/ip address
add address=192.168.200.39/24 interface=ether4 network=192.168.200.0
add address=192.168.0.1/24 interface=ether2 network=192.168.0.0
/ip dhcp-client
add disabled=no interface=ether1
/ip dhcp-server network
add address=192.168.0.0/24 gateway=192.168.0.1
/ip firewall filter
add action=accept chain=forward
add action=accept chain=input src-address=189.89.66.2
add action=accept chain=input src-address=172.16.1.0/30
add action=accept chain=input protocol=icmp
add action=drop chain=input
/ip firewall nat
add action=masquerade chain=srcnat out-interface=link src-address=192.168.0.0/24
/ip route
add distance=1 dst-address=189.89.66.2/32 gateway=192.168.200.1
/system identity
set name=RT-CLIENTE3
```

**Comment by wellyngton-sena** [comment]
Switch de acesso distribuído para a rede dos clientes: 

![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/151698059/523c6b62-d999-4f15-a444-d6e19d6ec512)

**Comment by wellyngton-sena** [comment]
O computador está conectado à internet, obtendo automaticamente um endereço IP por meio do protocolo DHCP, e é capaz de resolver nomes de domínio. Imagem demonstrando:
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/151698059/f73359b9-44e2-4521-81a3-2ce1026a24fe)
