### ISSUE TITLE
Configuração de servidor de monitoramento

### ISSUE THREAD

**Issue by fredericont** [Maxuelbm/ISP-Toolbox#14]

**Comment by Maxuelbm** [comment]
Durante a instalação do servidor, tivemos problemas na utilização da imagem do ubuntu disponibilizada pelo próprio PNETlab. Assim sendo, tivemos que utilizar o qemu para virtualizar o ubuntu e inserir no pnetlab. Segue abaixo os procedimentos realizados. 
![qemu-ubuntu](https://github.com/Maxuelbm/ISP-Toolbox/assets/54376718/273ed0af-e374-4f2d-a1fb-357a7ac89b7a)

**Comment by Maxuelbm** [comment]
Depois do sistema operacional inicializado dentro do PNETLAB, realizamos a configuração do Zabbix de acordo com a documentação do site oficial. Segue abaixo imagem do serviço operacional e da interface web do serviço.

Zabbix-Server:
![zabbix-service](https://github.com/Maxuelbm/ISP-Toolbox/assets/54376718/74c56da4-237a-498b-afde-8dfb729f81bb)

Zabbix Application:
![zabbix-web](https://github.com/Maxuelbm/ISP-Toolbox/assets/54376718/9e1d4711-7128-4904-838c-75e517a571b5)
