### ISSUE TITLE
Analisar o Firwall de todos os dispositivos

### ISSUE THREAD

**Issue by Maxuelbm** [Maxuelbm/ISP-Toolbox#18]
Validar se existe alguma brecha na configuração de Firewall dos dispositivos. Aplicar regras caso seja necessário.

**Comment by fredericotsmx** [comment]
Essas regras configuram o firewall no MikroTik para gerenciar o tráfego de rede. A primeira regra permite a passagem de todos os pacotes encaminhados. Em seguida, há regras específicas para aceitar pacotes de entrada referente de endereços IP designados, como 177.89.179.78, 177.52.37.146 e 189.89.66.2, bem como de sub-redes como 172.16.1.0/30, 10.100.100.0/24 e do IP 172.16.116.1. Além disso, a regra 8 permite pacotes ICMP (protocolo de controle de mensagens da Internet). Por fim, a última regra descarta todos os outros pacotes de entrada que não atendem às condições anteriores, garantindo um controle preciso sobre o tráfego na rede.


```
/ip firewall filter
add action=accept chain=forward
add action=accept chain=input src-address=177.89.179.78
add action=accept chain=input src-address=177.52.37.146
add action=accept chain=input src-address=189.89.66.2
add action=accept chain=input src-address=172.16.1.0/30
add action=accept chain=input src-address=10.100.100.0/24
add action=accept chain=input src-address=172.16.116.1
add action=accept chain=input protocol=icmp
add action=drop chain=input
```

**Comment by fredericont** [comment]
Essas regras configuram o firewall no MikroTik para gerenciar o tráfego de rede. A primeira regra permite a passagem de todos os pacotes encaminhados. Em seguida, há regras específicas para aceitar pacotes de entrada referente de endereços IP designados, como 177.89.179.78, 177.52.37.146 e 189.89.66.2, bem como de sub-redes como 172.16.1.0/30, 10.100.100.0/24 e do IP 172.16.116.1. Além disso, a regra 8 permite pacotes ICMP (protocolo de controle de mensagens da Internet). Por fim, a última regra descarta todos os outros pacotes de entrada que não atendem às condições anteriores, garantindo um controle preciso sobre o tráfego na rede.

```
/ip firewall filter
add action=accept chain=forward
add action=accept chain=input src-address=177.89.179.78
add action=accept chain=input src-address=177.52.37.146
add action=accept chain=input src-address=189.89.66.2
add action=accept chain=input src-address=172.16.1.0/30
add action=accept chain=input src-address=10.100.100.0/24
add action=accept chain=input src-address=172.16.116.1
add action=accept chain=input protocol=icmp
add action=drop chain=input
```
