### ISSUE TITLE
Criação da topologia inicial

### ISSUE THREAD

**Issue by Maxuelbm** [Maxuelbm/ISP-Toolbox#3]
Realizar o desenho da topologia lógica inicial. do projeto.

**Comment by wellyngton-sena** [comment]
![PNETLBA](https://github.com/Maxuelbm/ISP-Toolbox/assets/151698059/d360b338-7201-4feb-8cab-554f73bfa61d)

**Comment by wellyngton-sena** [comment]
A topologia de rede será configurado semelhante a imagem abaixo.

**Comment by wellyngton-sena** [comment]
![Uploading PNETLBA.png…]()

**Comment by wellyngton-sena** [comment]
![PNETLBA](https://github.com/Maxuelbm/ISP-Toolbox/assets/151698059/3bdf9b43-bef1-40a1-848e-fc9f6a96000d)

**Comment by wellyngton-sena** [comment]
A topologia de rede, conforme ilustrado na imagem, demonstra a utilização do PNETLab para emular o provedor de internet. Nesse cenário, serão empregados os principais protocolos de rede para provedores, tais como IP, CGNAT e DNS. Para assegurar a segurança, optaremos pelo protocolo de autenticação PPPoE.
No que diz respeito ao roteamento, adotaremos estratégias distintas: o roteamento estático será empregado para rotas simples, enquanto o OSPF será utilizado em situações de roteamento mais complexo. Para consolidar essa estrutura, os concentradores ACCEL-PPP e Mikrotik serão utilizados.
O sistema contará com dois servidores distintos: um destinado ao monitoramento e outro hospedado na nuvem, que desempenhará a função de servidor de autenticação RADIUS. Essa abordagem visa otimizar o desempenho e a eficiência da rede, proporcionando uma infraestrutura robusta e segura para o provedor de internet.
