### ISSUE TITLE
Segmentação e documentação do endereçamento da rede.

### ISSUE THREAD

**Issue by Maxuelbm** [Maxuelbm/ISP-Toolbox#4]
Realizar a segmentação e documentação do endereçamento de rede que será utilizando no projeto.

**Comment by fredericont** [comment]
Com base na topologia, definidos as seguintes faixas de IPs para as VLANs:
`
VLAN 10 - PPPoE2 | 172.16.1.0/30
VLAN 20 - PPPoE1 | 172.16.1.4/30
VLAN 30 - SERVIDOR | 172.16.10.0/30
VLAN 100 - REDE CLIENTES 1 | 10.100.100.0/24
VLAN 200 - REDE CLIENTES 2 | 10.200.200.0/24
`

**Comment by fredericont** [comment]
Com base na topologia, definidos as seguintes faixas de IPs para as VLANs:

> VLAN 10 - PPPoE2 | 172.16.1.0/30 
> VLAN 20 - PPPoE1 | 172.16.1.4/30 
> VLAN 30 - SERVIDOR | 172.16.10.0/30 
> VLAN 100 - REDE CLIENTES 1 | 10.100.100.0/24 
> VLAN 200 - REDE CLIENTES 2 | 10.200.200.0/24

**Comment by fredericont** [comment]
Topologia documentada: 
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/104873596/3e79f9cd-c6fa-46d4-9564-0775ce313f33)
