### ISSUE TITLE
Configurar dispositivos de rede

### ISSUE THREAD

**Issue by Maxuelbm** [Maxuelbm/ISP-Toolbox#6]
Realizar a configuração dos dispositivos de rede.

**Comment by wellyngton-sena** [comment]
Os dispositivos foram configurados da seguinte forma para garantir uma organização eficiente:

A eth1 do roteador de borda foi vinculada à eth1 do switch core. Além disso, os concentradores PPPoE 2 e 1 foram associados, respectivamente, às portas eth2 e eth3 do switch core. O servidor Zabbix foi configurado para operar na sua porta eth1 e vinculada na porta eth6 do switch core. Quanto aos switches de acesso 1 e 2, foram configurados nas portas eth4 e eth5 do switch core, conectando-se às portas que atendem os computadores dos clientes.


A estrutura da rede é centralizada no switch core, justificando seu nome, e todo o tráfego de saída para a internet é direcionado à borda, onde ocorre a filtragem tanto do acesso de entrada quanto de saída externa.

**Comment by wellyngton-sena** [comment]
![pnetlab configurando](https://github.com/Maxuelbm/ISP-Toolbox/assets/151698059/bbb41af8-d51a-4dd9-9985-79e4ed829dd8)
