### ISSUE TITLE
Configuração do Roteamento

### ISSUE THREAD

**Issue by fredericont** [Maxuelbm/ISP-Toolbox#7]

**Comment by Maxuelbm** [comment]
Para o roteamento configuramos um OSPF entre nossa borda com a internet e o servidor PPPoE 1 dos nossos clientes. Logo a nossa borda consegue alcançar a rede 10.100.100.0/24 destinada ao serviço PPPoE dos clientes, conforme imagem:
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/54376718/7035fb0a-50f3-4864-ab67-9a7931da9f2e)

Além disso, configuramos a borda como rota default de todos os roteadores que pertencem a área 0 do OSPF.
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/54376718/65adf4a2-8882-47dc-a0ec-d54f830e38fe)

**Comment by Maxuelbm** [comment]
Após concluir a configuração do OSPF, o servidor PPPoE 1 já aprende a rota default para nossa Borda.
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/54376718/85acff65-ca35-4011-9e49-5f12a1845f08)

**Comment by Maxuelbm** [comment]
Além da configuração do OSPF, no servidor PPPoE1 configuramos o PPPoE Server para discagem nos roteadores de cada cliente.
![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/54376718/de1ab8ef-f188-43a5-ac13-1699f76ebec7)

![image](https://github.com/Maxuelbm/ISP-Toolbox/assets/54376718/3a363b47-03d3-44a6-9c65-5f8f15bada8b)

**Comment by Maxuelbm** [comment]
Após discagem no roteador do cliente, a conectividade para internet foi realizada a partir do PC simulado em nosso ambiente. Segue imagens dos testes e do fluxo de comunicação do PC até a internet.
![roteamento-pnet](https://github.com/Maxuelbm/ISP-Toolbox/assets/54376718/b17860e9-7bb9-4234-88d5-0960804272d5)

![fluxo-pnet](https://github.com/Maxuelbm/ISP-Toolbox/assets/54376718/b4741f2d-1c82-493a-85e8-fd855d57bc49)
