### ISSUE TITLE
Definição das regras de NAT

### ISSUE THREAD

**Issue by fredericont** [Maxuelbm/ISP-Toolbox#9]

**Comment by wellyngton-sena** [comment]
Foram realizadas algumas configurações no firewall filter e NAT (Network Address Translation) no roteador MikroTik, visando melhorar a segurança e a eficiência da rede. Referente ao NAT, uma regra específica foi implementada para manipular o tráfego de saída da rede local 10.100.100.0/24 na interface ether2. A ação 'masquerade' foi aplicada a este tráfego, ocultando assim o endereço IP de origem e permitindo que a borda acesse a internet. A regra de masquerade é a seguinte:

`0    chain=srcnat action=masquerade src-address=10.100.100.0/24 out-interface=ether2 log=no log-prefix=""
`

Sobre às regras de firewall em filter rules, as configurações foram estabelecidas para permitir, filtrar e gerenciar o tráfego. As regras foram organizadas de forma a garantir a segurança da rede, permitindo apenas o tráfego necessário. Abaixo estão os detalhes das regras de firewall:

Regra que permite o encaminhamento de tráfego, assegurando a conectividade entre diferentes partes da rede:
`0    chain=forward action=accept
`

regras que permitem o tráfego de endereços IP específicos, garantindo a comunicação autorizada com determinados dispositivos.
```
1    chain=input action=accept src-address=189.89.66.2
2    chain=input action=accept src-address=170.80.156.130 log=no log-prefix=""
3    chain=input action=accept src-address=187.19.242.148 log=no log-prefix=""
4    chain=input action=accept src-address=172.16.1.0/30 log=no log-prefix=""
5    chain=input action=accept src-address=10.100.100.0/24 in-interface=v-1.10 log=no log-prefix=""
```

Regra que permite o tráfego ICMP, fundamental para a comunicação de diagnóstico e controle de rede.
`6    chain=input action=accept protocol=icmp log=no log-prefix=""
`

Regra final descarta qualquer tráfego que não tenha sido autorizado pelas regras anteriores. Fundamental para bloquear acessos não autorizados.
`7    chain=input action=drop log=no log-prefix=""`
